server:
  port: 8091


auth-server: http://localhost:9090 # authorization服务地址


security:
  oauth2:
    client:
      client-id: clinet
      client-secret: 123456
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key #解析jwt令牌所需要密钥的地址