server:
  port: 8080


# 做一个类似 security一样的默认登陆页面功能，进一步的理解 Spring Boot 的 默认配置含义及设计思想
#security:
#  login:
#    loginPage: /loginDemo.html

spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:3306}/security
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:zhao-324}
    driver-class-name:  com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379