server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3600/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


#
#security:
#  login:
#    loginPage: /loginDemo.html