server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.112.8.89:4466/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: swpu.mysql.root.1
    driver-class-name: com.mysql.jdbc.Driver


#
#security:
#  login:
#    loginPage: /loginDemo.html